items:
  - token: "import_rop_nodes"
    label: "Import ROP Nodes"
    command: "from project_tools import import_rop_nodes;reload(import_rop_nodes);import_rop_nodes.import_rop_nodes()"
  - token: "export_aov_list"
    label: "Export AOV Data"
    command: "from project_tools import import_rop_nodes;reload(import_rop_nodes);import_rop_nodes.export_aov_list()"
  - token: "update_aov_list"
    label: "Update AOVs"
    command: "from project_tools import import_rop_nodes;reload(import_rop_nodes);import_rop_nodes.update_aov_list()"
  - token: "ak_ttv_scene_collector"
    label: "Collect Scene"
    command: "from project_tools import scene_collector;reload(scene_collector);scene_collector.main()"
  - token: "create_bundles"
    label: "Create Bundles"
    command: "from project_tools import create_bundles;reload(create_bundles);create_bundles.create_bundles()"
  - token: "replace_debug_assets"
    label: "Replace Debug Assets"
    command: "from project_tools import replace_debug_assets;reload(replace_debug_assets);replace_debug_assets.main()"
